import  ExcalidrawDSLConverter  from "./src/converter.js";
import clipboard from "clipboardy"; // ✅ Node-compatible clipboard

const dslElement = [
  { id: "user", type: "rect", x: 100, y: 200, w: 100, h: 60, text: "User" },
  {
    id: "upload",
    type: "rect",
    x: 300,
    y: 200,
    w: 140,
    h: 60,
    text: "Upload Service",
  },
  {
    id: "s3raw",
    type: "rect",
    x: 500,
    y: 200,
    w: 140,
    h: 60,
    text: "S3 Raw Bucket",
  },
  { id: "sqs", type: "rect", x: 700, y: 200, w: 120, h: 60, text: "SQS Queue" },
  {
    id: "ecs",
    type: "rect",
    x: 900,
    y: 200,
    w: 180,
    h: 80,
    text: "ECS Fargate\nTranscoder",
  },
  {
    id: "s3hls",
    type: "rect",
    x: 1150,
    y: 200,
    w: 160,
    h: 60,
    text: "S3 Processed (HLS)",
  },
  {
    id: "cf",
    type: "rect",
    x: 1400,
    y: 200,
    w: 160,
    h: 60,
    text: "CloudFront CDN",
  },
  {
    id: "player",
    type: "rect",
    x: 1650,
    y: 200,
    w: 120,
    h: 60,
    text: "Video.js Player",
  },

  {
    id: "db",
    type: "rect",
    x: 900,
    y: 400,
    w: 160,
    h: 60,
    text: "MongoDB Metadata",
  },
  {
    id: "auth",
    type: "rect",
    x: 500,
    y: 400,
    w: 140,
    h: 60,
    text: "OAuth Service",
  },
  {
    id: "stripe",
    type: "rect",
    x: 1150,
    y: 400,
    w: 160,
    h: 60,
    text: "Stripe Billing",
  },

  {
    id: "a1",
    type: "arrow",
    x: 200,
    y: 230,
    endX: 300,
    endY: 230,
    startBind: "user",
    endBind: "upload",
  },
  {
    id: "a2",
    type: "arrow",
    x: 440,
    y: 230,
    endX: 500,
    endY: 230,
    startBind: "upload",
    endBind: "s3raw",
  },
  {
    id: "a3",
    type: "arrow",
    x: 640,
    y: 230,
    endX: 700,
    endY: 230,
    startBind: "s3raw",
    endBind: "sqs",
  },
  {
    id: "a4",
    type: "arrow",
    x: 820,
    y: 230,
    endX: 900,
    endY: 230,
    startBind: "sqs",
    endBind: "ecs",
  },
  {
    id: "a5",
    type: "arrow",
    x: 1080,
    y: 230,
    endX: 1150,
    endY: 230,
    startBind: "ecs",
    endBind: "s3hls",
  },
  {
    id: "a6",
    type: "arrow",
    x: 1310,
    y: 230,
    endX: 1400,
    endY: 230,
    startBind: "s3hls",
    endBind: "cf",
  },
  {
    id: "a7",
    type: "arrow",
    x: 1560,
    y: 230,
    endX: 1650,
    endY: 230,
    startBind: "cf",
    endBind: "player",
  },

  {
    id: "ecs-db",
    type: "arrow",
    x: 990,
    y: 280,
    endX: 990,
    endY: 400,
    startBind: "ecs",
    endBind: "db",
  },
  {
    id: "user-auth",
    type: "arrow",
    x: 200,
    y: 260,
    endX: 500,
    endY: 430,
    startBind: "user",
    endBind: "auth",
  },
  {
    id: "player-stripe",
    type: "arrow",
    x: 1710,
    y: 260,
    endX: 1230,
    endY: 400,
    startBind: "player",
    endBind: "stripe",
  },
];


const excalidrawElements = ExcalidrawDSLConverter.fromDSL(dslElement);

// Copy JSON string to clipboard
clipboard.writeSync(JSON.stringify(excalidrawElements, null, 2));

console.log("✅ Excalidraw elements copied to clipboard!");
